version: '3'
services:
  flask_app:
    build: .
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app
